# Generated by Django 5.2.4 on 2025-08-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('total_required', models.IntegerField(default=132)),
                ('major_required', models.IntegerField(default=50)),
                ('general_required', models.IntegerField(default=8)),
                ('drbol_required', models.IntegerField(default=18)),
                ('special_general_required', models.IntegerField(default=3)),
                ('sw_required', models.IntegerField(default=9)),
                ('msc_required', models.IntegerField(default=23)),
                ('major_must_courses', models.JSONField(help_text='전공 필수 과목명 및 학기 정보(JSON 형태)')),
                ('major_selective_courses', models.JSONField(blank=True, help_text='전공 선택 과목명 및 학기 정보(JSON 형태)', null=True)),
                ('general_must_courses', models.JSONField(blank=True, help_text='교양 필수 과목명 및 학기 정보(JSON 형태)', null=True)),
                ('general_selective_courses', models.JSONField(blank=True, help_text='일반선택 과목명 및 학기 정보(JSON 형태)', null=True)),
                ('special_general_courses', models.JSONField(blank=True, help_text='특성화교양 과목명 및 학기 정보(JSON 형태)', null=True)),
                ('sw_courses', models.JSONField(blank=True, help_text='SW/데이터활용역량 과목명 및 학기 정보(JSON 형태)', null=True)),
                ('msc_courses', models.JSONField(blank=True, help_text='MSC 과목명 및 학기 정보(JSON 형태)', null=True)),
                ('drbol_areas', models.TextField(help_text='드볼 영역 이름(콤마 구분)')),
                ('drbol_courses', models.JSONField(blank=True, help_text='드볼 영역별 과목 리스트(JSON 형태)', null=True)),
            ],
            options={
                'unique_together': {('major', 'year')},
            },
        ),
    ]
