# Generated by Django 5.2.18 on 2026-10-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationrequirement',
            name='drbol_rules',
            field=models.JSONField(blank=True, help_text='드볼 영역 규칙(JSON). 각 항목: {area, required_credit}', null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='drbol_areas',
            field=models.TextField(blank=True, help_text="(레거시) 드볼 영역 이름(콤마 구분). 예: '인문과예술,사회와문화,자연과기술'"),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='drbol_courses',
            field=models.JSONField(blank=True, help_text='드볼 영역별 과목 리스트(JSON). 키=area, 값=과목 배열(각 항목: {code, name, semester?, aliases?})', null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='general_must_courses',
            field=models.JSONField(blank=True, help_text='교양필수 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='general_selective_courses',
            field=models.JSONField(blank=True, help_text='일반선택(교양선택) 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='major_must_courses',
            field=models.JSONField(help_text='전공필수 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}'),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='major_selective_courses',
            field=models.JSONField(blank=True, help_text='전공선택 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='msc_courses',
            field=models.JSONField(blank=True, help_text='MSC 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='special_general_courses',
            field=models.JSONField(blank=True, help_text='특성화교양 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='sw_courses',
            field=models.JSONField(blank=True, help_text='SW/데이터활용역량 과목 리스트(JSON). 각 항목: {code, name, semester?, aliases?}', null=True),
        ),
    ]
