# Generated by Django 5.2.18 on 2026-10-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_restore_requirement_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationrequirement',
            name='legacy_data',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='graduationrequirement',
            name='source_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graduationrequirement',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
