# Generated by Django 5.2.18 on 2026-10-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_normalize_course_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('campus', models.CharField(default='서울', max_length=20)),
                ('admission_year_from', models.PositiveSmallIntegerField()),
                ('admission_year_to', models.PositiveSmallIntegerField()),
                ('curriculum_year', models.PositiveSmallIntegerField()),
                ('accreditation_track', models.CharField(choices=[('accredited', '공학교육 인증'), ('non_accredited', '비인증')], max_length=20)),
                ('version', models.CharField(max_length=80)),
                ('data', models.JSONField()),
                ('source_document', models.TextField()),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('major', 'campus', 'admission_year_from', 'admission_year_to', 'accreditation_track', 'version'), name='unique_requirement_ruleset_version')],
            },
        ),
    ]
