# Generated by Django 5.2.18 on 2026-10-09 12:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_program_rulesets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField()),
                ('sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('pdf_page', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('printed_page', models.CharField(max_length=40)),
                ('statement', models.TextField(help_text='Exact applicable statement, not an inferred code mapping')),
                ('official_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CourseIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(default='서울', max_length=20)),
                ('major', models.CharField(default='컴퓨터공학과', max_length=100)),
                ('academic_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('term', models.CharField(choices=[('1', '1'), ('2', '2'), ('summer', 'summer'), ('winter', 'winter')], max_length=10)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('classification', models.CharField(blank=True, max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='analysis.courseidentity')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.courseevidence')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('same_course', '동일과목'), ('replacement', '대체과목'), ('retake', '재수강 허용')], max_length=20)),
                ('policy_version', models.CharField(blank=True, max_length=80)),
                ('criterion_id', models.CharField(blank=True, max_length=80)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.courseevidence')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relations', to='analysis.courseversion')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='analysis.courseversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='courseversion',
            index=models.Index(fields=['campus', 'major', 'code', 'academic_year', 'term'], name='course_code_term_lookup'),
        ),
        migrations.AddConstraint(
            model_name='courseversion',
            constraint=models.UniqueConstraint(fields=('course', 'campus', 'major', 'academic_year', 'term'), name='course_exact_term_version'),
        ),
        migrations.AddConstraint(
            model_name='courserelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'kind', 'policy_version', 'criterion_id'), name='unique_course_relation_scope'),
        ),
    ]
