# Generated by Django 5.2.4 on 2025-08-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transcripts/')),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리 중'), ('done', '완료'), ('error', '오류')], default='pending', max_length=10)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transcripts/pages/')),
                ('page_number', models.PositiveIntegerField()),
            ],
        ),
    ]
