# Generated by Django 5.2.18 on 2026-10-08 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transcripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcript',
            name='confirmed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='legacy_status',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='ocr_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='ocr_raw_data',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
