# Generated by Django 5.2.18 on 2026-10-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accreditation_track',
            field=models.CharField(blank=True, choices=[('', '확인 필요'), ('accredited', '공학교육 인증'), ('non_accredited', '비인증')], default='', max_length=20),
        ),
    ]
